#!/usr/bin/env bash
LB_HOME="/opt/liquibase-4.3.0"
$LB_HOME/liquibase --driver="org.postgresql.Driver" \
--classpath="$LB_HOME/lib" \
--changeLogFile="databaseChangeLog.sql" \
--url="jdbc:postgresql://localhost:5432/masterjava" \
--username=user \
--password=password \
migrate